'use client';
import {useState,useEffect} from 'react';import {Check,ChevronRight,Download,Printer,QrCode,ShieldCheck,CalendarDays,History,Search,Coins} from 'lucide-react';import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Progress} from '@/components/ui/progress';import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';import {toast} from 'sonner';import {Asset,Role,roles,requestTypes,money,bookValue} from '@/shared/domain';import {printAssets} from '@/frontend/services/excel-export';import {Any,api,Badge,Pick,Empty,Metric,Pager,Activity,date} from '@/frontend/components/common';
export default function Operations({view,data,open,write,busy,revision,select,exportRows}:{view:string;data:Any;open:(k:string,a?:Any)=>void;write:(b:Any)=>Promise<any>;busy:boolean;revision:number;select:(a:Asset)=>void;exportRows:(a:Asset[])=>void}){
 const [roundId,setRoundId]=useState(''),[items,setItems]=useState<Any[]>([]),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const editable=['staff','admin'].includes(data.me.role),active:Asset[]=data.assets.filter((a:Asset)=>a.lifecycle==='active'),round=data.rounds.find((r:Any)=>r.id===roundId);
 useEffect(()=>{if(!roundId&&data.rounds.length)setRoundId(data.rounds[0].id);},[data.rounds,roundId]);
 useEffect(()=>{setPage(0);},[view,search,roundId]);
 useEffect(()=>{if(roundId)api('?view=stocktake&round='+encodeURIComponent(roundId)).then(r=>setItems(r.items)).catch(e=>toast.error(e.message));},[roundId,revision]);
 if(view==='requests')return <><div className="notice">สายอนุมัติสำหรับคำขอใหม่: เจ้าหน้าที่ → {JSON.parse(data.settings.workflow||'["head","deputy","dean"]').map((r:Role)=>roles[r]).join(' → ')}<p className="mt-1">คำขอเดิมใช้สายอนุมัติ ณ เวลาที่ส่ง</p></div><div className="panel"><div className="panel-head"><h2>คำขอทั้งหมด <span className="badge ml-2">{data.requests.length}</span></h2><span className="caption">สร้างคำขอจากรายละเอียดครุภัณฑ์</span></div>{data.requests.map((r:Any)=>{const chain=JSON.parse(r.chain) as Role[];return <article className="request-card" key={r.id}><div className="request-title"><div><b>{requestTypes[r.kind as keyof typeof requestTypes]} · {r.name}</b><p className="mono">{r.code}</p></div><Badge value={r.status}/></div><p>{r.reason}</p>{r.kind==='transfer'&&<p>ปลายทาง: {JSON.parse(r.payload).location} · {JSON.parse(r.payload).branch}</p>}<div className="step-chain">{chain.map((role,i)=><span key={role} className={'step '+(i<r.stage?'done':i===r.stage&&r.status==='pending'?'current':'')}>{i+1}. {roles[role]}</span>)}</div>{data.approvals.filter((a:Any)=>a.requestId===r.id).map((a:Any)=><p key={a.id} className="caption">{a.actorName||a.actor} · {a.decision==='approve'?'อนุมัติ':'ส่งกลับ'} · {a.note||'ไม่มีหมายเหตุ'} · {date(a.createdAt)}</p>)}<div className="actions mt-3"><span className="caption">ส่งเมื่อ {date(r.createdAt)}</span>{r.status==='pending'&&chain[r.stage]===data.me.role&&r.actor!==data.me.id&&<><Button size="sm" onClick={()=>open('approve',{request:r})}><Check size={15}/>อนุมัติ</Button><Button variant="outline" size="sm" onClick={()=>open('reject',{request:r})}>ส่งกลับ</Button></>}</div></article>})}{!data.requests.length&&<Empty title="ยังไม่มีคำขอ"><p>เปิดรายละเอียดครุภัณฑ์เพื่อส่งคำขอโอนย้าย ซ่อม หรือจำหน่าย</p></Empty>}</div></>;
 if(view==='stocktakes'){
 const filtered=items.filter(i=>(i.code+' '+i.name).includes(search));
 return <><div className="two-col"><div className="panel"><div className="panel-head"><h2>รอบตรวจนับ</h2><CalendarDays size={20}/></div><div className="panel-body">{data.rounds.map((r:Any)=><button key={r.id} className="block w-full text-left mb-5" onClick={()=>setRoundId(r.id)}><div className="flex justify-between gap-3"><b>{r.name}</b><Badge value={r.status}/></div><Progress className="count-progress" value={r.total?r.checked/r.total*100:0}/><p className="caption">ปีงบประมาณ {r.year} · ตรวจแล้ว {r.checked} / {r.total} รายการ</p></button>)}{!data.rounds.length&&<Empty title="ยังไม่มีรอบตรวจนับ"/>}</div></div><div className="panel"><div className="panel-head"><h2>ตรวจนับผ่าน QR</h2><QrCode size={20} className="text-blue-600"/></div><div className="panel-body"><p className="text-sm">สแกน QR ด้วยกล้องโทรศัพท์เพื่อเปิดรายละเอียด จากนั้นเลือกรอบตรวจนับและบันทึกผล หรือค้นหาหมายเลขในรายการด้านล่าง</p><div className="notice mt-4">ผลตรวจนับเก็บแยกจากสถานะในทะเบียน หากพบชำรุดบางส่วน ให้ใช้ “แบ่งล็อต” เพื่อแยกยอดภายหลัง</div></div></div></div>{round&&<div className="panel"><div className="panel-head"><h2>{round.name}</h2>{editable&&round.status==='open'&&<Button variant="outline" disabled={busy||round.checked!==round.total} onClick={()=>write({action:'closeRound',id:round.id})}>ปิดรอบตรวจนับ</Button>}</div><div className="toolbar"><div className="searchbox"><Search/><Input placeholder="ค้นหาชื่อหรือรหัสในรอบนี้…" aria-label="ค้นหารายการตรวจนับ" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><Table className="source-table"><TableHeader><TableRow><TableHead>ครุภัณฑ์</TableHead><TableHead className="text-center">จำนวนตามทะเบียน</TableHead><TableHead className="text-center">พบจริง</TableHead><TableHead className="text-center">ผลตรวจ</TableHead><TableHead>เวลาบันทึก</TableHead><TableHead className="w-[100px] text-right"/></TableRow></TableHeader><TableBody>{filtered.slice(page*40,(page+1)*40).map(i=><TableRow key={i.id}><TableCell><b>{i.name}</b><p className="mono">{i.code}</p></TableCell><TableCell className="text-center">{JSON.parse(i.snapshot).quantity}</TableCell><TableCell className="text-center">{i.quantity??'—'}</TableCell><TableCell className="text-center">{i.result==='pending'?<span className="badge">ยังไม่ตรวจ</span>:<Badge value={i.result}/>}</TableCell><TableCell>{i.checkedAt?date(i.checkedAt):'—'}</TableCell><TableCell className="text-right">{editable&&round.status==='open'&&<Button size="sm" variant="outline" onClick={()=>open('check',{item:i})}>บันทึกผล</Button>}</TableCell></TableRow>)}</TableBody></Table><Pager page={page} total={filtered.length} onChange={setPage}/></div>}</>;
 }
 if(view==='reports'){
 const groups=Object.entries(active.reduce((o:Record<string,number>,a)=>{o[a.branch]=(o[a.branch]||0)+a.totalSatang;return o;},{})).sort((a,b)=>b[1]-a[1]);const soon=active.filter(a=>{if(!a.receivedDate||!a.lifeYears)return false;const end=new Date(a.receivedDate).getTime()+a.lifeYears*365.25*86400000;return end>=Date.now()&&end<=Date.now()+2*365.25*86400000;});
 return <><div className="two-col"><div className="panel"><div className="panel-head"><h2>มูลค่าทุนตามสาขา</h2><Button variant="outline" size="sm" disabled={!active.length||busy} onClick={()=>exportRows(active)}><Download size={16}/>Excel</Button></div><div className="panel-body">{groups.map(([b,v])=><div className="bar-row" key={b}><div className="bar-label"><span>{b}</span><b>{money(v)} บาท</b></div><div className="bar-track"><div className="bar-fill" style={{width:(v/Math.max(1,...groups.map(x=>x[1]))*100)+'%'}}/></div></div>)}{!active.length&&<Empty title="ยังไม่มีข้อมูลสำหรับรายงาน"/>}</div></div><div className="panel"><div className="panel-head"><h2>อายุใช้งานและมูลค่าคงเหลือ</h2></div><div className="panel-body"><Metric label="มูลค่าคงเหลือที่คำนวณได้" value={money(active.reduce((n,a)=>n+(bookValue(a)??0),0))} note="บาท · เฉพาะรายการที่วันที่รับและอายุใช้งานครบ" icon={Coins}/><div className="notice">ค่าเสื่อมเส้นตรงตามวันใช้งาน ÷ (อายุใช้งาน × 365.25 วัน) หักถึงมูลค่าซากที่กำหนด เป็นค่าประมาณเพื่อวางแผน</div><p className="text-sm">ข้อมูลอายุใช้งานไม่ครบ {active.filter(a=>bookValue(a)===null).length} รายการ · ใกล้ครบอายุภายใน 2 ปี {soon.length} รายการ</p></div></div></div><div className="panel"><div className="panel-head"><h2>รายละเอียดมูลค่าคงเหลือ</h2><Button variant="outline" size="sm" disabled={!active.length} onClick={()=>printAssets(active)}><Printer size={16}/>พิมพ์ทะเบียน</Button></div><Table className="source-table"><TableHeader><TableRow><TableHead>รายการ</TableHead><TableHead>วันที่รับ</TableHead><TableHead>อายุใช้งาน</TableHead><TableHead className="text-right">มูลค่าทุน</TableHead><TableHead className="text-right">มูลค่าคงเหลือ</TableHead></TableRow></TableHeader><TableBody>{active.slice(page*40,(page+1)*40).map(a=><TableRow key={a.id}><TableCell><button className="asset-name" onClick={()=>select(a)}>{a.name}</button><p className="mono">{a.code}</p></TableCell><TableCell>{a.receivedDate||'ยังไม่ระบุ'}</TableCell><TableCell>{a.lifeYears?a.lifeYears+' ปี':'ยังไม่ระบุ'}</TableCell><TableCell className="num">{money(a.totalSatang)}</TableCell><TableCell className="num">{bookValue(a)===null?'ข้อมูลยังไม่ครบ':money(bookValue(a)!)}</TableCell></TableRow>)}</TableBody></Table><Pager page={page} total={active.length} onChange={setPage}/></div></>;
 }
 if(view==='audit')return <div className="panel"><div className="panel-head"><h2>ประวัติล่าสุด 100 เหตุการณ์</h2><History size={20}/></div><div className="panel-body">{data.events.map((e:Any)=><div key={e.id}><Activity event={e}/><details className="text-sm mb-3"><summary className="cursor-pointer text-blue-700">ดูค่าก่อนและหลัง</summary><pre className="text-xs overflow-auto bg-slate-50 p-4 my-2 rounded">{JSON.stringify({ก่อน:JSON.parse(e.before),หลัง:JSON.parse(e.after)},null,2)}</pre></details></div>)}{!data.events.length&&<Empty title="ยังไม่มีเหตุการณ์บันทึก"/>}</div></div>;
 if(view==='users'&&data.me.role==='admin')return <><div className="role-grid">{Object.entries(roles).map(([r,label])=><div className="role-card" key={r}><ShieldCheck size={23}/><b>{label}</b><p>{({staff:'ทะเบียน นำเข้า QR คำขอ และตรวจนับ',head:'ตรวจสอบและอนุมัติขั้นที่ 1',deputy:'ตรวจสอบและอนุมัติขั้นที่ 2',dean:'ตรวจสอบและอนุมัติขั้นสุดท้าย',admin:'ผู้ใช้ สิทธิ์ ตั้งค่าระบบ และดูแลทะเบียน'} as Any)[r]}</p></div>)}</div><div className="panel"><div className="panel-head"><h2>บัญชีผู้ใช้</h2><span className="caption">อีเมลต้องตรงกับบัญชีที่เข้าสู่ระบบ</span></div><Table className="source-table"><TableHeader><TableRow><TableHead>ชื่อ / อีเมล</TableHead><TableHead>บทบาท</TableHead><TableHead>สถานะ</TableHead><TableHead className="w-[110px] text-right"/></TableRow></TableHeader><TableBody>{[...data.users,...data.invites.filter((i:Any)=>!data.users.some((u:Any)=>u.email===i.email)).map((i:Any)=>({...i,id:i.email,invited:true}))].map((u:Any)=><TableRow key={u.id}><TableCell><b>{u.name}</b><p>{u.email}</p></TableCell><TableCell>{roles[u.role as Role]}</TableCell><TableCell>{!u.active?'ระงับสิทธิ์':u.invited?'รอเข้าสู่ระบบ':'ใช้งาน'}</TableCell><TableCell className="text-right"><Button variant="outline" size="sm" onClick={()=>open('user',{user:u})}>แก้ไขสิทธิ์</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="panel"><div className="panel-head"><h2>สายอนุมัติสำหรับคำขอใหม่</h2></div><div className="panel-body"><p className="text-sm mb-4">Admin ดูแลระบบ และไม่มีสิทธิ์อนุมัติคำขอทางธุรกิจแทนผู้บริหาร</p><Pick label="สายอนุมัติ" value={data.settings.workflow||'["head","deputy","dean"]'} onChange={v=>write({action:'workflow',chain:JSON.parse(v)})} options={[[JSON.stringify(['head','deputy','dean']),'หัวหน้าสำนักงาน → รองฝ่ายบริการ → คณบดี'],[JSON.stringify(['head']),'หัวหน้าสำนักงาน'],[JSON.stringify(['dean']),'คณบดี']]}/></div></div></>;
 return null;
}

